// This file was generated by src/cmd/generate-error-map
// based on docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json.
// Please DON'T change this file directly!!!
// Apply your changes in docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json
// and run `npm run generate-error-map` instead.
export const ErrorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
    USER_AUTH_ERROR: 'USER_AUTH_ERROR',
    REQUEST_FORBIDDEN_ERROR: 'REQUEST_FORBIDDEN_ERROR',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    UNPROCESSABLE_ENTITY_ERROR: 'UNPROCESSABLE_ENTITY_ERROR',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

export const ErrorCodeMap: Record<ErrorCode, number> = {
    VALIDATION_ERROR: 400,
    API_VALIDATION_ERROR: 400,
    USER_AUTH_ERROR: 401,
    REQUEST_FORBIDDEN_ERROR: 403,
    ITEM_NOT_FOUND: 404,
    ROUTE_NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY_ERROR: 422,
    RATE_LIMIT_EXCEEDED: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVER_ERROR: 500,
};
