import fs from 'fs';
import SwaggerParser from '@apidevtools/swagger-parser';
import schemaHttpCode from './schema-http-code.json';

const SPEC_PATH = './docs/openapi.yaml';
const OUT_PATH = './src/domain/errors.ts';

type SpecWithErrorSchemas = {
    components?: {
        schemas?: Record<string, { properties?: { error_code?: { enum?: string[] } } }>;
    };
};

const HEADER = `// This file was generated by src/cmd/generate-error-map
// based on docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json.
// Please DON'T change this file directly!!!
// Apply your changes in docs/openapi.yaml & src/cmd/generate-error-map/schema-http-code.json
// and run \`npm run generate-error-map\` instead.
`;

async function collectErrorCodes(): Promise<[code: string, status: number][]> {
    const spec = (await SwaggerParser.parse(SPEC_PATH)) as SpecWithErrorSchemas;

    return Object.entries(schemaHttpCode).flatMap(([schemaName, status]) => {
        const codes = spec.components?.schemas?.[schemaName]?.properties?.error_code?.enum;
        if (!codes) {
            throw new Error(`${SPEC_PATH}: #/components/schemas/${schemaName}/properties/error_code/enum not found`);
        }
        return codes.map((code): [string, number] => [code, status]);
    });
}

function render(entries: [string, number][]): string {
    const codes = entries.map(([code]) => `    ${code}: '${code}',`).join('\n');
    const statuses = entries.map(([code, status]) => `    ${code}: ${status},`).join('\n');

    return `${HEADER}export const ErrorCodes = {
${codes}
} as const;

export type ErrorCode = keyof typeof ErrorCodes;

export const ErrorCodeMap: Record<ErrorCode, number> = {
${statuses}
};
`;
}

collectErrorCodes()
    .then((entries) => {
        fs.writeFileSync(OUT_PATH, render(entries));
        console.log(`Generated ${OUT_PATH}`); // eslint-disable-line no-console
    })
    .catch((err: unknown) => {
        console.error(err); // eslint-disable-line no-console
        process.exit(1);
    });
